#pragma once

#include <Jitter2/Precision.hpp>
#include <Jitter2/ArgumentCheck.hpp>
#include <Jitter2/DebugCheck.hpp>
#include <Jitter2/IDebugDrawer.hpp>
#include <Jitter2/Logger.hpp>
#include <Jitter2/Tracer.hpp>
#include <Jitter2/Collision/CollisionIsland.hpp>
#include <Jitter2/Collision/CollisionFilter/IBroadPhaseFilter.hpp>
#include <Jitter2/Collision/CollisionFilter/INarrowPhaseFilter.hpp>
#include <Jitter2/Collision/CollisionFilter/TriangleEdgeCollisionFilter.hpp>
#include <Jitter2/Collision/DynamicTree/DynamicTree.hpp>
#include <Jitter2/Collision/DynamicTree/IDynamicTreeProxy.hpp>
#include <Jitter2/Collision/IslandHelper.hpp>
#include <Jitter2/Collision/NarrowPhase/CollisionManifold.hpp>
#include <Jitter2/Collision/NarrowPhase/ConvexPolytope.hpp>
#include <Jitter2/Collision/NarrowPhase/MinkowskiDifference.hpp>
#include <Jitter2/Collision/NarrowPhase/NarrowPhase.hpp>
#include <Jitter2/Collision/NarrowPhase/SimplexSolver.hpp>
#include <Jitter2/Collision/NarrowPhase/SimplexSolverAB.hpp>
#include <Jitter2/Collision/NarrowPhase/SupportPrimitives.hpp>
#include <Jitter2/Collision/Shapes/BoxShape.hpp>
#include <Jitter2/Collision/Shapes/CapsuleShape.hpp>
#include <Jitter2/Collision/Shapes/ConeShape.hpp>
#include <Jitter2/Collision/Shapes/ConvexHullShape.hpp>
#include <Jitter2/Collision/Shapes/CylinderShape.hpp>
#include <Jitter2/Collision/Shapes/ICloneableShape.hpp>
#include <Jitter2/Collision/Shapes/PointCloudShape.hpp>
#include <Jitter2/Collision/Shapes/Shape.hpp>
#include <Jitter2/Collision/Shapes/ShapeHelper.hpp>
#include <Jitter2/Collision/Shapes/SphereShape.hpp>
#include <Jitter2/Collision/Shapes/TriangleMesh.hpp>
#include <Jitter2/Collision/Shapes/TriangleShape.hpp>
#include <Jitter2/Collision/Shapes/TransformedShape.hpp>
#include <Jitter2/Collision/Shapes/VertexSupportMap.hpp>
#include <Jitter2/Dynamics/Constraints/AngularMotor.hpp>
#include <Jitter2/Dynamics/Constraints/BallSocket.hpp>
#include <Jitter2/Dynamics/Constraints/ConeLimit.hpp>
#include <Jitter2/Dynamics/Constraints/Constraint.hpp>
#include <Jitter2/Dynamics/Constraints/ConstraintUtility.hpp>
#include <Jitter2/Dynamics/Constraints/DistanceLimit.hpp>
#include <Jitter2/Dynamics/Constraints/FixedAngle.hpp>
#include <Jitter2/Dynamics/Constraints/HingeAngle.hpp>
#include <Jitter2/Dynamics/Constraints/Limit.hpp>
#include <Jitter2/Dynamics/Constraints/LinearMotor.hpp>
#include <Jitter2/Dynamics/Constraints/PointOnLine.hpp>
#include <Jitter2/Dynamics/Constraints/PointOnPlane.hpp>
#include <Jitter2/Dynamics/Constraints/TwistAngle.hpp>
#include <Jitter2/Dynamics/Arbiter.hpp>
#include <Jitter2/Dynamics/ArbiterKey.hpp>
#include <Jitter2/Dynamics/Contact.hpp>
#include <Jitter2/Dynamics/Joints/HingeJoint.hpp>
#include <Jitter2/Dynamics/Joints/Joint.hpp>
#include <Jitter2/Dynamics/Joints/PrismaticJoint.hpp>
#include <Jitter2/Dynamics/Joints/UniversalJoint.hpp>
#include <Jitter2/Dynamics/Joints/WeldJoint.hpp>
#include <Jitter2/Dynamics/RigidBody.hpp>
#include <Jitter2/Dynamics/World.hpp>
#include <Jitter2/LinearMath/JAngle.hpp>
#include <Jitter2/LinearMath/JBoundingBox.hpp>
#include <Jitter2/LinearMath/JMatrix.hpp>
#include <Jitter2/LinearMath/JQuaternion.hpp>
#include <Jitter2/LinearMath/JTriangle.hpp>
#include <Jitter2/LinearMath/JVector.hpp>
#include <Jitter2/LinearMath/MathHelper.hpp>
#include <Jitter2/LinearMath/StableMath.hpp>
#include <Jitter2/Parallelization/Parallel.hpp>
#include <Jitter2/Parallelization/ReaderWriterLock.hpp>
#include <Jitter2/Parallelization/ThreadPool.hpp>
#include <Jitter2/DataStructures/PartitionedSet.hpp>
#include <Jitter2/DataStructures/ShardedDictionary.hpp>
#include <Jitter2/DataStructures/SlimBag.hpp>
#include <Jitter2/SoftBodies/BroadPhaseCollisionFilter.hpp>
#include <Jitter2/SoftBodies/DynamicTreeCollisionFilter.hpp>
#include <Jitter2/SoftBodies/SoftBody.hpp>
#include <Jitter2/SoftBodies/SoftBodyShape.hpp>
#include <Jitter2/SoftBodies/SoftBodyTetrahedron.hpp>
#include <Jitter2/SoftBodies/SoftBodyTriangle.hpp>
#include <Jitter2/SoftBodies/SpringConstraint.hpp>
#include <Jitter2/Unmanaged/PartitionedBuffer.hpp>
